spring:
  codec:
    max-in-memory-size: 4194304
  r2dbc:
    url: "r2dbc:h2:file:////config/manajer;AUTO_SERVER=TRUE;DATABASE_TO_LOWER=TRUE;"
    username: root
    password: root
    pool:
      enable: true
      initial-size: 1
      max-size: 10
      max-idle-time: 5m
      validation-query: SELECT 1
#  sql:
#    init:
#      mode: always

manajer:
  base-path: /api

