name: Docker Image CI

env:
  IMAGE_NAME: manajer

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven

    - name: Print Build Environment
      working-directory: manajer-api
      run: |
        java -version
        ./mvnw --version

    - name: Set environment variables
      working-directory: manajer-api
      run: |
        echo "VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout --file pom.xml)" >> $GITHUB_ENV
        echo "YYMMDD=$(date +'%y%m%d')" >> $GITHUB_ENV

    - name: Build with Maven
      working-directory: manajer-api
      run: mvn -DskipTests=true -B package --file pom.xml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

#    - name: Build and push Docker images
#      uses: docker/build-push-action@v4.1.1
#      working-directory: manajer-api
#      with:
#        context: .
#        push: true
#        platforms: linux/amd64,linux/arm64
#        tags: |
#          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
#          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-${{ env.YYMMDD }}.${{ github.run_number }}
#
